<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<section class="container-fluid  formAddSampling">
    <h1 class="text-center m-5 title-asso">Enregistrement des tris</h1>
    <form class="m-5 d-flex flex-column justify-content-center align-items-center" action="Data/triPost" method="POST">
        <div class="mb-3">
        </div>
        <i class="bi bi-plus-square-fill ajout_ligne">Ajouter un tri</i><br>
        <input type="submit" value="Valider" id="submit" class="btn btn-success">

    </form>
</section>
<script src="public/javascript/select.js"></script>