<div class="row">
    <div class="col pie-chart">
        <canvas id="pie-type-sea"></canvas>

    </div>
    <div class="col  pie-chart">
        <canvas id="pie-color-sea"></canvas>
    </div>
    <div class="col  pie-chart">
        <canvas id="pie-size-sea"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="public/javascript/chart.js"></script>