<table class="table table-responsive table-hover table-striped table-bordered table-dark  text-center ">
    <thead>
        <tr>
            <th scope="col">Température de l'eau</th>
            <th scope="col">Volume filtré</th>
            <th scope="col">Etat de la mer</th>
            <th scope="col">Heure de départ</th>
            <th scope="col">Force du vent</th>
            <th scope="col">Commentaires</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $details["Temperature_C"] ?></td>
            <td><?= $details["Volume_filtered_m3"] ?></td>
            <td><?= $details["Sea_state_B"] ?></td>
            <td><?= $details["Start_time_UTC"] ?></td>
            <td><?= $details["Wind_force_B"] ?></td>
            <td><?= $details["Commentaires"] ?></td>
        </tr>
    </tbody>
</table>

<div class="row">
    <div class="col pie-chart">
        <canvas id="pie-type-sample"></canvas>

    </div>
    <div class="col pie-chart">
        <canvas id="pie-color-sample"></canvas>
    </div>
    <div class="col pie-chart">
        <canvas id="pie-size-sample"></canvas>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="public/javascript/chart.js"></script>